services:
  nats1:
    image: nats:latest
    container_name: nats1
    command: ["-c","/etc/nats/nats.conf","--server_name","nats1","-m","8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - nats1-data:/data

  nats2:
    image: nats:latest
    container_name: nats2
    command: ["-c","/etc/nats/nats.conf","--server_name","nats2","-m","8222"]
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6223:6222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - nats2-data:/data

  nats3:
    image: nats:latest
    container_name: nats3
    command: ["-c","/etc/nats/nats.conf","--server_name","nats3","-m","8222"]
    ports:
      - "4224:4222"
      - "8224:8222"
      - "6224:6222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - nats3-data:/data

  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    depends_on: [nats1, nats2]
    entrypoint: ["sleep","infinity"]

volumes:
  nats1-data: {}
  nats2-data: {}
  nats3-data: {}